[project]
name = "sentinel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Antigro09", email = "anthonyj.cavero@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "arc-agi>=0.9.9",
    "mlx>=0.32.0",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
